# configure the settings and URL handlers for the app engine application
application: silicon-monitor-180615
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
  DJANGO_SETTINGS_MODULE: 'appengine-storage-site.settings'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"